from forecastHurricane import ForecastHurricane
from forecastStorm import ForecastStorm
from forecastTornado import ForecastTornado
from sunnyToday import SunnyToday
from sunnyTomorrow import SunnyTomorrow
from randomPredictor import RandomPredictor
